language: objective-c
osx_image: xcode10.2

language: objective-c
cache: cocoapods

before_install:
- gem update cocoapods
- pod repo update
- pod install

script:
  - set -o pipefail && xcodebuild -workspace Httper.xcworkspace -scheme Httper -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO | xcpretty -c 
